name: Run tests

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
  # Create a matrix of all tests
  discover-tests:
    runs-on: ubuntu-latest

    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
      - uses: actions/checkout@v4

      - id: set-matrix
        run: |
          TESTS=$(find testfiles -name "*.c" | jq -R -s -c 'split("\n")[:-1]')
          echo "matrix=$TESTS" >> $GITHUB_OUTPUT

  prepare-antlr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Restore ANTLR cache
        id: antlr-cache
        uses: actions/cache@v4
        with:
          path: ~/antlr4-install
          key: ${{ runner.os }}-antlr4-4.13.2

      - name: Install ANTLR (if cache miss)
        if: steps.antlr-cache.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake unzip wget g++
          mkdir -p ~/antlr4-install
          cd ~/antlr4-install
          wget -q https://www.antlr.org/download/antlr-4.13.2-complete.jar
          wget -q https://www.antlr.org/download/antlr4-cpp-runtime-4.13.2-source.zip
          unzip -q antlr4-cpp-runtime-4.13.2-source.zip
          mkdir -p build
          cd build
          cmake -DCMAKE_INSTALL_PREFIX:PATH=$HOME/antlr4-install/ ..
          make -j8
          make install

  # Run each tests
  test-suite:
    needs: [discover-tests, prepare-antlr]
    strategy:
      fail-fast: false # To continue running all tests even if one fails
      matrix:
        arch: [x86_64, arm64]
        test-file: ${{ fromJson(needs.discover-tests.outputs.matrix) }}

    runs-on: ${{ matrix.arch == 'arm64' && 'ubuntu-24.04-arm' || 'ubuntu-latest' }}
    name: Test ${{ matrix.test-file }} (\${{ matrix.arch }})


    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Restore ANTLR cache
        uses: actions/cache@v4
        with:
          path: ~/antlr4-install
          key: ${{ runner.os }}-antlr4-4.13.2

      - name: Create config.mk
        run: |
          # Création du fichier de config avec les chemins standards Ubuntu
          echo "ANTLRJAR=$HOME/antlr4-install/antlr-4.13.2-complete.jar" > compiler/config.mk
          echo "ANTLRINC=$HOME/antlr4-install/include/antlr4-runtime/" >> compiler/config.mk
          echo "ANTLRLIB=$HOME/antlr4-install/lib/libantlr4-runtime.a" >> compiler/config.mk

      - name: Compile
        run: make -C compiler

      - name: Run single test
        run: python3 ifcc-test.py ${{ matrix.test-file }}